version: "3.8"

services:
  app:
    build: .
    ports:
      - "8080:8080"


  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: postgres123!
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgres/data


volumes:
  postgres-data:
